### ISSUE TITLE
Supports life cycle callbacks for user processor

### ISSUE THREAD

**Issue by killme2008** [sofastack/sofa-bolt#123]
**Is your feature request related to a problem? Please describe.**

User processors may have some resources when processing requests, such as file, database conenction etc.

But current user processors doesn't have life cycle mechanism, we can't initialize or destroy resources explictly.

**Describe the solution you'd like**

UserProcessor adds callback methods:

```
// Initialize the user processor
public void init();
//Destroy the user processor.
public void destroy();
```

And the framework will call these callback methods in start or shutdown. These new methods should have default implementations by using java8' s default method.

**Comment by fengjiachun** [comment]
Another way is to check whether the user processor implements the interface 'Lifecycle'. If so, execute the init / destroy method?

**Comment by dbl-x** [comment]
这个可能会在1.6的版本中去支持，原1.6的开发计划已经包含了统一生命周期的接口。
接口统一后再考虑UserProcessor增加生命周期的能力。
另外是否基于1.8提供default实现这个要考虑当前使用的情况，也许需要兼容当前1.6的方式，提供默认实现，用户有需要时进行覆盖。

**Comment by dbl-x** [comment]
附1.6开发计划：https://github.com/alipay/sofa-bolt/wiki/Bolt-1.6.0%E5%BC%80%E5%8F%91%E8%AE%A1%E5%88%92
