### ISSUE TITLE
ProtocolCode的设计真的支持以byte[]作为version吗？

### ISSUE THREAD

**Issue by dbl-x** [sofastack/sofa-bolt#126]
### Your question

ProtocolCode类的设计以byte[]作为入参，支持version为一个byte数组。但是其他类都只支持以byte作为ProtocolCode，比如DefaultInvokeFuture的protocol属性是byte类型的，是不是实际上无法使用byte[]作为ProtocolCode？

另外ProtocolManager提供了registerProtocol(Protocol protocol, byte... protocolCodeBytes)的接口，但是并没有提供unregisterProtocol(byte... protocolCodeBytes)的方法。

假设通过registerProtocol(Protocol protocol, byte... protocolCodeBytes)方法注册了一个protocol，入参为一个byte[]，值为[0,1]，这个注册的protocol是无法通过unRegisterProtocol(byte protocolCode)取消的，因为unregister并没有构建出一个和[0,1]相同的ProtocolCode。

所以总体来看，并没有支持以byte[]作为ProtocolCode。

### Your scenes

明确ProtocolCode的使用方式，优化代码实现。

### Your advice

* 简化ProtocolCode，以byte作为参数
* 优化ProtocolManager的API设计
* 代码内不在定义byte PROTOCOL_CODE这样的常量，而应该是ProtocolCode PROTOCOL_CODE = ...

或者干脆就是byte类型，没有封装类型。

### Environment

- SOFABolt version: all version
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by cytnju** [comment]
底层核心需求实际是Bolt支持自定义协议，但是目前支持不友好，DB组是自己继承覆盖了一些类来实现的，这个是长远要支持的一个事情。
