### ISSUE TITLE
BaseRemoting invokeSync BUG反馈

### ISSUE THREAD

**Issue by RobertoHuang** [sofastack/sofa-bolt#127]
在发送同步请求时如果发生异常，处理逻辑
conn.removeInvokeFuture(request.getId());
if (future != null) {
    future.putResponse(commandFactory.createSendFailedResponse(conn.getRemoteAddress(), e));
}
logger.error("Exception caught when sending invocation, id={}", request.getId(), e);

实际上if判断中的future应为conn.removeInvokeFuture(request.getId());的返回值

**Comment by dbl-x** [comment]
具体哪个类多少行代码麻烦发一下
