### ISSUE TITLE
RpcProtocol# RpcCommandDecoder 解码类中注释错误，有点误导

### ISSUE THREAD

**Issue by smalldok** [sofastack/sofa-bolt#142]
### RpcProtocol # RpcCommandDecoder 解码类中注释错误，有点误导
版本：release/1.6.0
问题：源码中代码逻辑没问题，只是注释有点误导，可以更正下
问题描述：
RpcProtocol 协议请求命令，第一个字段是ProtocolCode
![640](https://user-images.githubusercontent.com/13725783/55387306-c5ca3f00-5563-11e9-829b-0ae810b5f5ee.jpg)

然而代码中的注释却是如下：
![clipboard](https://user-images.githubusercontent.com/13725783/55387584-3ffac380-5564-11e9-8d56-eef970c9c4ed.png)

**Comment by dbl-x** [comment]
@smalldok 下面的version指明的是Protocol的version
