### ISSUE TITLE
TLS support wanted

### ISSUE THREAD

**Issue by firebat** [sofastack/sofa-bolt#149]
**Is your feature request related to a problem? Please describe.**
我们的系统跨机房部署，初步方案为 nginx / https 走rest接口，这就需要开发人员做许多额外的工作（协议转换，HA 等），而Router、负载均衡、这些策略在现有众多的rpc框架中已经做的很好了，只需添加TLS支持即可，再外部无法提供更多安全支持或更复杂的情况下，以最小代价达到安全通信。

**Describe the solution you'd like**
Bolt基于Netty实现，增加SSL支持代价较小。RpcServer 添加

    bolt.ssl.switch=false|true
    bolt.ssl.keystore=<keystore-file>
    bolt.ssl.keystore.password=<keystore-file-password>
    bolt.ssl.keystore.type=pcks12

RpcClient使用的Url增加`useSSL=true`，开启Netty的SslHandler。

**Describe alternatives you've considered**

**Additional context**
RpcServer容易修改，改动量比较小。

    ChannelPipeline pipeline = channel.pipeline();
    if (sslSwitch) {
        pipeline.addLast("sslHandler", new SslHandler(createSslContext().newEngine(channel.alloc())));
    }
    pipeline.addLast("decoder", codec.newDecoder());
    pipeline.addLast("encoder", codec.newEncoder());

客户端需要调整的略多，AbstractConnectionFactory的ChannelInitializer需要调整，在createConnection的时候根据Url的配置去构造Handler列表。

    protected Channel doCreateConnection(String targetIP, int targetPort, int connectTimeout)
                                                                                             throws Exception {
        //
        ......
        bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectTimeout)
                         .handler(new ChannelInitializer<SocketChannel>() {

            @Override
            protected void initChannel(SocketChannel channel) {
                ChannelPipeline pipeline = channel.pipeline();
                if (url.useSSL()) {
                    pipeline.addLast("sslHandler", new SslHandler(createSslContext().newEngine(channel.alloc())));
                }

**Comment by dbl-x** [comment]
@firebat 可以提PR来解决这个问题；目前规划版本暂无此功能。

**Comment by zongtanghu** [comment]
This feature request is much more import!We need it! @dbl-x

**Comment by killme2008** [comment]
I am working on this feature, and the PR will be created today.

**Comment by cytnju** [comment]
fixed  #197
