### ISSUE TITLE
RpcTaskScanner为什么需要这个Scanner

### ISSUE THREAD

**Issue by gumandy** [sofastack/sofa-bolt#150]
RpcClient为什么需要这个巡检线程去检查连接是否断开？
channel.closeFuture可以注册FutureListener监听断开事件不能满足需求吗？

**Comment by cytnju** [comment]
@gumandy hi，处理问题晚了。这个设计的考虑是一个兜底的措施，目前的bolt实现中`Channel`和`Connection`是相互绑定的，但是无法去做到这个绑定是原子性的，也就是说存在创建了`Connection`但是`Channel`是NULL的情况，详见 #168 。因此为了防止内存污染以及潜在的泄露问题，需要这样一个扫描线程去通过`Connection#isFine`巡检连接是否完好可用。
