### ISSUE TITLE
DefaultConnectionManager#DefaultConnectionManager(ConnectionSelectStrategy connectionSelectStrategy)

### ISSUE THREAD

**Issue by WangShuangQuan-A** [sofastack/sofa-bolt#153]
DefaultConnectionManager(ConnectionSelectStrategy connectionSelectStrategy) 此方法调用this()首先会创建一个this.connectionSelectStrategy = new RandomSelectStrategy(globalSwitch)然后再由入参覆盖，这样子写好吗？
代码如下：
public DefaultConnectionManager() {
        this.connTasks = new ConcurrentHashMap<>();
        this.healTasks = new ConcurrentHashMap<>();
        this.connectionSelectStrategy = new RandomSelectStrategy(globalSwitch);
    }

    public DefaultConnectionManager(ConnectionSelectStrategy connectionSelectStrategy) {
        this();
        this.connectionSelectStrategy = connectionSelectStrategy;
    }

**Comment by dbl-x** [comment]
@WangShuangQuan-A 这不是一段好的代码实现，将在下一个版本修复。也欢迎直接提PR修复这个问题！
