### ISSUE TITLE
DefaultConnectionManager重复实现Scannable 接口

### ISSUE THREAD

**Issue by WangShuangQuan-A** [sofastack/sofa-bolt#154]
ConnectionManager接口已经继承Scannable，DefaultConnectionManager有必要再实现Scannable吗？
如下：
public class DefaultConnectionManager implements ConnectionManager, ConnectionHeartbeatManager, Scannable 
public interface ConnectionManager extends Scannable

**Comment by dbl-x** [comment]
非必须，只是一个编码习惯，把接口带上了
