### ISSUE TITLE
HashMap使用问题

### ISSUE THREAD

**Issue by WangShuangQuan-A** [sofastack/sofa-bolt#155]
如果不获取值用containsKey()就好了，如果要获取值，containsKey()和get()核心逻辑一致，算资源浪费吗
例如：DefaultConfigContainer#get(ConfigType configType, ConfigItem configItem)
        if (userConfigs.containsKey(configType)) {
            return (T) userConfigs.get(configType).get(configItem);
        }

**Comment by dbl-x** [comment]
userConfigs.containsKey(configType)可能返回true但是值是null（map中存入了一个value为null的键值对），这样下一步再get会NPE

**Comment by WangShuangQuan-A** [comment]
我的意思是get一次，对value加个非空判断，不是更好，避免同一key多次get

**Comment by WangShuangQuan-A** [comment]
我的意思是GET一次，对值加个非空判断，不是更好，避免同一键多次获得

**Comment by dbl-x** [comment]
> 我的意思是get一次，对value加个非空判断，不是更好，避免同一key多次get

这个确实是的，这块可以改一下，欢迎提PR修改
