### ISSUE TITLE
BoltClient这个类中的方法 RpcResponseFuture invokeWithFuture()返回值类型定死，子类无法自定义协议返回值

### ISSUE THREAD

**Issue by 939347507** [sofastack/sofa-bolt#164]
### Your question
BoltClient这个类中的方法 RpcResponseFuture invokeWithFuture(final Connection conn, final Object request, int timeoutMillis)返回值类型定死为RpcResponseFuture，这个类的实现不是应该与具体的协议实现无关吗？但是却用到了rpc包中的类， 我现在是完全自定义协议， 自己写了个类继承了AbstractBoltClient， 但是现在根本没办法重写invokeWithFuture方法了，因为返回值类型被定死为 RpcResponseFuture了，而不是自己协议的Future
describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version: 1.6.0
- JVM version (e.g. `java -version`): 
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
当前确实是这样，对于你这种完全自定义协议的模式支持不够友好，后续的版本中会去解决这个问题

**Comment by 939347507** [comment]
我使用sofa-bolt并不是为了使用rpc, 而是服务端和客户端自己定制协议进行长连接通讯，本身目前项目已使用netty实现，  但是更方便的使用4种请求响应模型(oneway、request/response 、callback、future)所以才使用bolt

**Comment by dbl-x** [comment]
> 我使用sofa-bolt并不是为了使用rpc, 而是服务端和客户端自己定制协议进行长连接通讯，本身目前项目已使用netty实现， 但是为了更方便的使用4种基础通信模型(oneway、request/response 、callback、future)所以才使用bolt

嗯，理解你的场景，后续的版本我们会逐步的剥离开“协议”和“框架”，你这个场景实际你是框架用户，后续我们会支持，欢迎关注。

**Comment by 939347507** [comment]
> > 我使用sofa-bolt并不是为了使用rpc, 而是服务端和客户端自己定制协议进行长连接通讯，本身目前项目已使用netty实现， 但是为了更方便的使用4种基础通信模型(oneway、request/response 、callback、future)所以才使用bolt
> 
> 嗯，理解你的场景，后续的版本我们会逐步的剥离开“协议”和“框架”，你这个场景实际你是框架用户，后续我们会支持，欢迎关注。

目前给我的感觉就是要想自定义协议实现，基本上要把command、encoder、decoder、EventHandler、InvokeFuture、BaseRemoting、CommandHandler、processor、CommandFacory类似于rpc的一整套一个不漏的要实现一遍，成本不是一般的大啊, 要把整个rpc的实现完全理解才能做出一个自己的定制协议

**Comment by dbl-x** [comment]
> > > 我使用sofa-bolt并不是为了使用rpc, 而是服务端和客户端自己定制协议进行长连接通讯，本身目前项目已使用netty实现， 但是为了更方便的使用4种基础通信模型(oneway、request/response 、callback、future)所以才使用bolt
> > 
> > 
> > 嗯，理解你的场景，后续的版本我们会逐步的剥离开“协议”和“框架”，你这个场景实际你是框架用户，后续我们会支持，欢迎关注。
> 
> 目前给我的感觉就是要想自定义协议实现，基本上要把command、encoder、decoder、EventHandler、InvokeFuture、BaseRemoting、CommandHandler、processor、CommandFacory类似于rpc的一整套一个不漏的要实现一遍，成本不是一般的大啊, 要把整个rpc的实现完全理解才能做出一个自己的定制协议

当前阶段你要实现其实也没有你说的这么复杂，你在上层包一层你自己的业务对象，实现自己的encoder\decoder，内部自己转成一个FakeRemotingCommand也可以实现，没有你想象的这么大，大多数都定义了接口，比如CommandFacory，你提供特定的实现即可。

**Comment by cytnju** [comment]
如果没有别的问题的话，这个issue先关闭了，如果还有其他问题欢迎另开issue : )
