### ISSUE TITLE
是否可以自定义心跳协议

### ISSUE THREAD

**Issue by sharfy** [sofastack/sofa-bolt#165]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
如果是要定制心跳的，可以自己实现一个请求作为心跳。
