### ISSUE TITLE
是否有golang版本bolt的计划

### ISSUE THREAD

**Issue by wangyjx** [sofastack/sofa-bolt#167]
不知道到哪里提这个问题，所以就发这里了。

是否有go版本bolt的计划，已经支持了python, node了，其实作为编写服务的语言，go可能比前面这两个用的更多。

看见sofa-mosn里面已经支持了bolt协议，何不干脆做个go版本的sofa-bolt和rpc

**Comment by dbl-x** [comment]
目前没有这方面的计划，你可以尝试把MOSN这块单独拎出来贡献go版本的Bolt。
