### ISSUE TITLE
Allow users to set SO_SNDBUF

### ISSUE THREAD

**Issue by JervyShi** [sofastack/sofa-bolt#171]
**Is your feature request related to a problem? Please describe.**
For this patch https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.9.184&id=caa51edc7e9606418611e6 , The linux kernel fixed an issue where an application would punish in a lower SO_SNDBUF configuration.

**Describe the solution you'd like**
Allow users to set `SO_SNDBUF` config.

**Describe alternatives you've considered**

**Additional context**

**Comment by cytnju** [comment]
we will add this feature next version.
