### ISSUE TITLE
为什么DefaultBizContext的put/get方法都是空实现？

### ISSUE THREAD

**Issue by xiaoma20082008** [sofastack/sofa-bolt#174]
### Your question

为什么DefaultBizContext的put/get方法都是空实现？

### Your scenes

没有调用getInvokeContext()#put/get是有什么特殊考虑吗？

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version: 1.6
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by cytnju** [comment]
@xiaoma20082008 这是一个Bolt的历史问题。当时的考虑是：

1. 通信上下文与业务上下文区分，所有以RemotingContext以及BizContext两个结构，分别在preHandle和hanlde方法中露出。
2. 部分必要的Remoting参数，可以在BizContext中对外使用，所以专门开了方法，比如获取ip，port等通信层的参数。
3. 综上，业务上下文里的参数，独立定义，默认通信层不需要（业务层需要的话自己定义），所以仅提供了接口get/set，没有默认实现。
