### ISSUE TITLE
Can I use the 808 protocol on sofa-bolt?

### ISSUE THREAD

**Issue by jewin** [sofastack/sofa-bolt#179]
### Your question

计划在sofa-bolt上使用808协议，请问除了替换编解码协议以外，还需要做哪些工作呢？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`): jdk8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
@jewin 目前Bolt集成了一个比较通用的，进过多年验证的协议，推荐使用。Bolt目前对用户使用特定其他的协议的支持还不是很友好，需要通过修改比较多的源码才能实现。

**Comment by calebzhao** [comment]
这个要改很多的扩展，我以前也是有自定义协议的需求，改过相当多的代码，你可以看看我去年改的，
https://gitee.com/passion/netty-protocol-skd.git
src\main\test里有测试代码

**Comment by jewin** [comment]
3q，这个场景已经通过自定义扩展完成了。
