### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by lqjack** [sofastack/sofa-bolt#181]
**Is your feature request related to a problem? Please describe.**

When the end user send the request to the server, then will construct the ip + port to build the Uri object. after that construct the connection , finally pass the parameters to the channel to netty to send the real invoke. Once the request arrives to the server , the server side should do the same reverted.

**Describe the solution you'd like**

Just one abstract is enough to do that. 

redefine the new Class named URI, just parse the string from the end user, then directly pass the parameter to the channel. The same to the server side. 

**Describe alternatives you've considered**

**Additional context**

**Comment by dbl-x** [comment]
This part is not a core performance issue, so there is not much optimization. However, this is a good suggestion, welcome to submit a PR to solve this problem.

**Comment by lqjack** [comment]
@dbl-x could provide the the main performance issue ?
