### ISSUE TITLE
url parse error

### ISSUE THREAD

**Issue by lqjack** [sofastack/sofa-bolt#182]
**Describe the bug**

When the test case fail to parse the format : 
sofatest-2.stack.alipay.net/10.209.155.54:12200 -> sofatest-2.stack.alipay.net/127.0.0.1/10.209.155.54:12200

### Expected behavior

assert failed. 

### Actual behavior

should refactor the parser to support the case 

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`): 1.8.0_66,
- OS version (e.g. `uname -a`):Darwin MacBook-Pro-2.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
- Maven version:Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T02:41:47+08:00)
- IDE version: IDEA 2019.02

**Comment by dbl-x** [comment]
@lqjack Please provide a Bolt version of the test.

**Comment by lqjack** [comment]
1.6.0

**Comment by cytnju** [comment]
@lqjack Could you please describe the test error more clearly ? I am afraid that I can not understand the description

> sofatest-2.stack.alipay.net/10.209.155.54:12200 -> sofatest-2.stack.alipay.net/127.0.0.1/10.209.155.54:12200 

clearly.
