### ISSUE TITLE
PortScan ServerSocket ss may be null

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [sofastack/sofa-bolt#187]
### Your question
ss 可能是null,未做判断处理,会引起空指针异常
https://github.com/sofastack/sofa-bolt/blob/3e2e8090ceabb06f3c2799ead3a1614589fe272c/src/test/java/com/alipay/remoting/rpc/common/PortScan.java#L41
当 new ServerSocket()抛出异常时
https://github.com/sofastack/sofa-bolt/blob/3e2e8090ceabb06f3c2799ead3a1614589fe272c/src/test/java/com/alipay/remoting/rpc/common/PortScan.java#L34
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by cytnju** [comment]
欢迎提PR解决

**Comment by QiAnXinCodeSafe** [comment]
好的，后续提交
