### ISSUE TITLE
NormalStringCustomSerializer&#39;s reset method has a bug

### ISSUE THREAD

**Issue by YANGJINJUE** [sofastack/sofa-bolt#190]
![image](https://user-images.githubusercontent.com/32013488/67443875-3f796580-f639-11e9-809a-f4b0383ad630.png)
应该一个是序列化一个是反序列化

**Comment by cytnju** [comment]
欢迎提PR解决这个问题。

**Comment by cytnju** [comment]
fixed . [pr](https://github.com/sofastack/sofa-bolt/pull/191)
