### ISSUE TITLE
How to get a random port?

### ISSUE THREAD

**Issue by Artoriasn** [sofastack/sofa-bolt#196]
### Your question
如何获取随机端口？
describe your question clearly
` RpcServer rpcServer = new RpcServer(0, true, true);
rpcServer.port() 仍然是0？`

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by cytnju** [comment]
@Artoriasn 你好，我看了下具体的方法实现，bolt确实存在这个随机端口无法正确现象，这个BUG会在最近修复。也欢迎你提PR解决。

**Comment by cytnju** [comment]
see #199
