### ISSUE TITLE
Multiple calls to the RpcClient # getConnection method fail to keep the connection persistent

### ISSUE THREAD

**Issue by Synex-wh** [sofastack/sofa-bolt#210]
**Describe the bug**

### 现象

- 因为注册中心后台需要保持两个服务节点间的链接，因为系统内存满或者其他原因导致断链后，希望持续调用com.alipay.remoting.rpc.RpcClient#getConnection(com.alipay.remoting.Url, int)方法，保证链接

- 目前发现系统持续调用此方法的任务一直执行，但是获取到的Connection对象为null，体现为这两个节点断链，没有再进行重连

- 进行内存dump查明，com.alipay.remoting.DefaultConnectionManager#connTasks这个对象对应链接的ip+port为key的RunStateRecordedFutureTask存在，并且其中反馈的outcome对象ConnectionPool也不为null，但ConnectionPool中的Connection列表没有数据isempty，这样每次即使调用getConnection方法返回的一直是null的connection对象，并且不会触发重新建联，因为建联方式必须connTasks里面关于这个key的task清理掉才会再次触发task.run才会触发

![image](https://user-images.githubusercontent.com/8018119/70888770-08617800-201c-11ea-816f-54cfdf0adc6d.png)

- 查看代码，这个RunStateRecordedFutureTask对象清理只有通过IO断链事件触发com.alipay.remoting.DefaultConnectionManager#remove(com.alipay.remoting.Connection)进行清理，或者定时任务RpcTaskScanner触发com.alipay.remoting.DefaultConnectionManager#scan进行清理，但是这个清理任务事件判断怀疑有问题

![image](https://user-images.githubusercontent.com/8018119/70889032-9c334400-201c-11ea-9a7a-3d9578778409.png)

- 故，综上所述，这个task有一定几率无法删除导致，持续调用getConnection方法无法正常保证链接可以重建

### Environment

- SOFABolt version:1.5.2
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by cytnju** [comment]
@Synex-wh 你能够提供一些bolt的日志来帮忙定位这个问题吗？目前看确实存在bug导致连接池中的连接为空无法重连的情况，但正常情况下走断链事件会触发连接池清除的逻辑，不应该会出现空连接池的情况的，希望能够多提供一些日志方便排查下。

**Comment by dbl-x** [comment]
背景：用户的bolt版本是1.5.2版本，应用出现过FullGC
分析问题出现的可能：
* 用户应用出现FullGC，创建Channel和创建Connection是一个非原子的操作，这样可能在Channel断开的时候没有执行ConnectionManager#remove(Connection)方法
* ConnectionManager#remove(Connection)没有执行，那么ConnectionPool里面会维持着不可用的连接，直到ConnectionPool#scan时将Connection从ConnectionPool中移除——并不会移除ConnectionPool对应的RunStateRecordedFutureTask
* RunStateRecordedFutureTask在ConnectionManager#scan时如果ConnectionPool不包含Connection并且accessTime超过了一段时间，RunStateRecordedFutureTask会被移除——在应用的使用中，用户会不断的getConnection，这样会更新accessTime导致RunStateRecordedFutureTask不会被移除
* 综合上面几点导致了用户出现一个ConnectionPool里面没有Connection，但是又无法通过RpcClient#getConnection创建出新的连接的问题

解决办法：
* 断连时Channel没有关联Connection的场景，通过兜底的方法将Connection从ConnectionPool中移除，并且移除Connection后校验ConnectionPool是否不包含连接，如果是，将对应的RunStateRecordedFutureTask移除
