### ISSUE TITLE
A bug that may cause write memory overflow

### ISSUE THREAD

**Issue by moyuguixiong** [sofastack/sofa-bolt#215]
我看框架中设置了WRITE_BUFFER_WATER_MARK，但是写的时候没有做如下判断，是不是可能会导致写内存溢出？           
            if (conn.getChannel().isWritable()){
                conn.getChannel().writeAndFlush();
            }

**Comment by cytnju** [comment]
@moyuguixiong 这个是netty框架相关的配置，你可以看下```ChannelOutboundBuffer```这个类中的代码实现；简单来说，netty的channelPipeline会在被触发write方法时，会比较当前待发送区的size和highWaterMark从而设置unwritable的数值，如果unwritable被更新成0，那么就说明无法写入了。所以并不会造成内存溢出，只会限制在高水位以内。

**Comment by moyuguixiong** [comment]
@cytnju 
ChannelOutboundBuffer的addMessage方法，每次都是先增加entry节点，再判断是否设置unwritable，而且不管unwritable是什么状态，都会增加entry节点。高并发情况下，如果网络出现异常，还一直调用addMessage方法(原因是调用writeAndFlush()方法前，没有判断isWritable())，写数据就会堆积，引发OOM，我分析netty源码是这样的，如果不对还请指正

**Comment by cytnju** [comment]
@moyuguixiong 我明白你的意思了，你说bolt在写channel的时候没有去判断isWritable，我记得是有判断的，你看下```DefaultConnectionFactory#check```这个方法，里面是会对connection做检查的。
![image](https://user-images.githubusercontent.com/23069836/77839401-ecd74300-71ae-11ea-8318-c52090b02ba0.png)
感谢你对bolt的关注，如果发现还有上述的问题，欢迎提PR修复它。

**Comment by moyuguixiong** [comment]
@cytnju 看到了，是在DefaultConnectionManager#check()实现了检查是否可写的能力，感谢解答！
