### ISSUE TITLE
Support runs on istio?

### ISSUE THREAD

**Issue by Divernia** [sofastack/sofa-bolt#216]
### Your question

Blot protocol support runs on istio?

**Comment by cytnju** [comment]
@Divernia Do you mean bolt golang sdk? if so, we don't have a plan for that yet.

**Comment by Divernia** [comment]
> @Divernia Do you mean bolt golang sdk? if so, we don't have a plan for that yet.

I mean, can I use istio as a service mesh using bolt protocol in sofa-rpc.

**Comment by cytnju** [comment]
> > @Divernia Do you mean bolt golang sdk? if so, we don't have a plan for that yet.
> 
> I mean, can I use istio as a service mesh using bolt protocol in sofa-rpc.

You'd better ask RPC for help, I'm afriad that I can not answer this question.

**Comment by Divernia** [comment]
> > > @Divernia Do you mean bolt golang sdk? if so, we don't have a plan for that yet.
> > 
> > 
> > I mean, can I use istio as a service mesh using bolt protocol in sofa-rpc.
> 
> You'd better ask RPC for help, I'm afriad that I can not answer this question.

Ok, thanks a lot.
