### ISSUE TITLE
ByteBuf引用计数问题

### ISSUE THREAD

**Issue by moyuguixiong** [sofastack/sofa-bolt#221]
com.alipay.remoting.rpc.RpcHandler重写了io.netty.channel.ChannelInboundHandlerAdapter#channelRead方法，这个方法不会自动释放ByteBuf的引用，追踪消息的处理路径
com.alipay.remoting.rpc.protocol.RpcRequestProcessor#dispatchToUserProcessor使用完消息后，没有释放消息的引用计数，会不会造成对象池泄露，并进而造成内存溢出？还是框架中有引用释放的地方，我没有找到

**Comment by IndiraFinish** [comment]
其实第一个channelInboundHandler是BytetoMessageDecoder，然后fire到你的com.alipay.remoting.rpc.RpcHandler,最终在BytetoMessageDecoder会帮你释放ByteBuf的引用的

**Comment by moyuguixiong** [comment]
@IndiraFinish 好的，感谢解答
