### ISSUE TITLE
[SoC] Split framework and private protocol banding, support user-defiend protocol

### ISSUE THREAD

**Issue by dbl-x** [sofastack/sofa-bolt#224]
## Introduction
SOFABolt is a lightweight, easy to use and high performance remoting framework based on Netty. Over the years, we have solved many problems in network communication in microservices and message middleware. We have deposited the summarized solution into the basic component of SOFABolt, so that more scenarios that use network communication can benefit from the unified.

## Target
In current SOFABolt implementation, the private protocol is directly coupled with overall framework. When use SOFABolt, you need use the built-in private protocol. When you want to use your own custom protocol, you need to do some more challenging code expansion to achieve it. Therefore, we hope to do some refactoring to the SOFABolt protocol framework to support quick and easy integration of user-defined protocols.

* Decoupling protocol framework and private protocol implementation

## 简介
SOFABolt是一个基于 Netty 最佳实践的轻量、易用、高性能、易扩展的通信框架。 这些年我们在微服务与消息中间件在网络通信上解决过很多问题，我们把总结出的解决方案沉淀到 SOFABolt 这个基础组件里，让更多的使用网络通信的场景能够统一受益。 

## 目标
当前的SOFABolt实现中私有协议是直接和整体框架耦合在一起的，在使用SOFABolt的同时需要使用提供的私有协议，当用户希望使用自己的自定义协议时需要进行比较有挑战的代码拓展才能实现。因此我们希望对SOFABolt的协议框架做一些重构以支持快速方便的集成用户的自定义协议。

* 解耦协议框架和具体私有协议实现

**Comment by AbelSara** [comment]
I am very interested in this idea. May I ask if I can communicate with you?

**Comment by ujjboy** [comment]
@AbelSara  可以参见 https://github.com/sofastack/sofa-bolt/issues/223  在官网提交提案申请。

**Comment by dbl-x** [comment]
> I am very interested in this idea. May I ask if I can communicate with you?

@AbelSara apply here：https://developer.aliyun.com/topic/summerofcode2020
and my e-mail: mark.lx@antfin.com

**Comment by AbelSara** [comment]
@ujjboy @dbl-x  thx!

**Comment by yunfeiyanggzq** [comment]
ASOC is great,I will work hard for it.

**Comment by byene0923** [comment]
I see that ASoC is over，Is this project been done by others？ If not， could I do that for the rest time of this year？ I have a great interest in SofaBolt！
