### ISSUE TITLE
About the JDK version

### ISSUE THREAD

**Issue by junjie-tang99** [sofastack/sofa-bolt#226]
### Your question
Now our RPC framework of credit card core system is based on rabbitmq. Recently we suppose to upgrade the communication framework to sofa-bolt. But our project's JDK version is JDK6. So I want to know whether the sofa-bolt can run well under the JDK6 environment. If it can run which version can support?

**Comment by dbl-x** [comment]
> ### Your question
> Now our RPC framework of credit card core system is based on rabbitmq. Recently we suppose to upgrade the communication framework to sofa-bolt. But our project's JDK version is JDK6. So I want to know whether the sofa-bolt can run well under the JDK6 environment. If it can run which version can support?

all version support jdk6
