### ISSUE TITLE
How to deal with the same class in different packages?

### ISSUE THREAD

**Issue by hutaishi** [sofastack/sofa-bolt#237]
**Is your feature request related to a problem? Please describe.**
client size  class is  common2.RequestBody, server side class is  common.RequestBody. the two class belong to diffreent package。
客户端和服务端有2个相同的请求体类， 但是客户端和服务端的包名不一样。目前的bolt对这种情况无法处理。
也就是说必须类的全限定名相同。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hutaishi** [comment]
另外HessianSerializer类的序列化是有问题的。1.String classOfT  这个参数根本没用到。  2. 很容易序列化成HashMap。
![image](https://user-images.githubusercontent.com/12478263/90325240-b8242680-dfab-11ea-847d-4a9a04bd4b2f.png)

**Comment by medusar** [comment]
通常情况下，两个类就是必须保持一致的，类名不同是无法转换的

**Comment by khotyn** [comment]
Java 两个相同的类，必须全限定类名是相同的。所以不同 package 下的类就是是不同的类。
