### ISSUE TITLE
通信协议中RequestType字段为什么有request, response两种类型

### ISSUE THREAD

**Issue by rsqzrcy** [sofastack/sofa-bolt#238]
### Your question
通信协议中RequestType字段为什么有request, response两种类型，是和双工通信相关吗？
### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:1.6.2
- JVM version (e.g. `java -version`):jdk8
- OS version (e.g. `uname -a`):macos
- Maven version:3.6.3
- IDE version:idea2020/2

**Comment by dbl-x** [comment]
是的，标记是一个请求包还是一个响应包，进行不同的逻辑处理。
