### ISSUE TITLE
线程数是否可以支持配置呢

### ISSUE THREAD

**Issue by bobbylv** [sofastack/sofa-bolt#246]
### Your question

使用中因为外在原因，需要对进程进行内存限制，如果在核数较多的系统上使用，实际上业务不需要这么多worker线程

### Your scenes

public abstract class AbstractConnectionFactory implements ConnectionFactory {

    private static final Logger         logger      = BoltLoggerFactory
                                                        .getLogger(AbstractConnectionFactory.class);

    private static final EventLoopGroup workerGroup = NettyEventLoopUtil.newEventLoopGroup(Runtime
                                                        .getRuntime().availableProcessors() + 1,
                                                        new NamedThreadFactory(
                                                            "bolt-netty-client-worker", true));

    private final ConfigurableInstance  confInstance;
    private final Codec                 codec;
    private final ChannelHandler        heartbeatHandler;
    private final ChannelHandler        handler;

    protected Bootstrap                 bootstrap;

### Your advice

线程数指定处是否可以支持配置呢？
如SystemPropertyUtil.getInt(
                                                                              "bolt.netty.worker.available_processors", Runtime
                                                                                  .getRuntime().availableProcessors())
来指定呢？

### Environment

- SOFABolt version:1.6.2
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
这是一个优先考虑性能的最佳实践。欢迎你提PR来优化这部分实现，使它支持用户配置。
