### ISSUE TITLE
报文格式能否完全支持自定义

### ISSUE THREAD

**Issue by mufanh** [sofastack/sofa-bolt#251]
### Your question

今年才开始仔细看sofa-bolt，发现对于报文这一块，PROTOCOL和VERSION会占用前面几位，能否让报文完全支持完全自定义，否则对于存量的协议，这些限制导致不方便使用

### Your scenes

比如现在想使用这个做一个服务代理，发现对报文有限制，就不方便直接使用

### Your advice

有没有比较好的方式支持

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
这个功能已经考虑过了，正在实现中。
目前的问题是用户需要完全自定义报文的话需要继承修改的类太多，对用户来说太难用了。

**Comment by mufanh** [comment]
嗯嗯，我先按照我的想法看看能否有比较好的方式接入，谢谢
