### ISSUE TITLE
 com.alipay.remoting.exception.RemotingException: Check connection failed for address

### ISSUE THREAD

**Issue by qinliang373** [sofastack/sofa-bolt#254]
### Your question
做为图片服务，上传图片有时会报如下异常，导致上传失败。在什么情况下会导致这种异常发生？
Caused by: com.alipay.remoting.exception.RemotingException: Check connection failed for address: Origin url [bolt://X.X.X.X:20113?accepts=100000&appNam
e=oss-provider&weight=100&language=java&pid=24729&interface=com.test.StorageFacade&timeout=0&serialization=hessian2&protocol=bolt&delay=
-1&dynamic=true&startTime=1611211023168&id=storageService&uniqueId=&rpcVer=50501], Unique key [x.x.x.x:20113]., maybe write overflow!
describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
  <dependency>
                <groupId>com.alipay.sofa</groupId>
                <artifactId>sofaboot-dependencies</artifactId>
                <version>3.1.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
- JVM version (e.g. `java -version`):
jdk1.8
- OS version (e.g. `uname -a`):
  centos 
- Maven version:
- IDE version:

**Comment by khotyn** [comment]
你可以看看设置下下面的两个参数：

```
-Dbolt.netty.buffer.high.watermark=XXXX
-Dbolt.netty.buffer.low.watermark=XXXX
```

* High 目前的默认值是：`Integer.toString(64 * 1024);`
* Low 目前的默认值是：`Integer.toString(32 * 1024);`

可以调大点儿看看。

**Comment by 892513490** [comment]
> 你可以看看设置下下面的两个参数：
> 
> ```
> -Dbolt.netty.buffer.high.watermark=XXXX
> -Dbolt.netty.buffer.low.watermark=XXXX
> ```
> 
> * High 目前的默认值是：`Integer.toString(64 * 1024);`
> * Low 目前的默认值是：`Integer.toString(32 * 1024);`
> 
> 可以调大点儿看看。

试过了，问题依然存在
