### ISSUE TITLE
对Connection中的poolkeys的疑惑

### ISSUE THREAD

**Issue by wqzaxy** [sofastack/sofa-bolt#257]
### Your question
Connection对象不应该是对应一个poolkey（ip:port）吗？为什么Connection中还会持有poolkey的集合？

### Environment

- SOFABolt version: 1.6.2
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):Linux lfs8 4.19.141+
- Maven version:3.6
- IDE version:

**Comment by dbl-x** [comment]
Bolt是一个通用的框架，可以进行业务的拓展。一些场景下连接会被复用，比如poolKey可以不是ip:port，而是你自己业务定义的Key。
