### ISSUE TITLE
如果用sofa-bolt来做代理，是否应该在server端获取到请求后，然后通过自定义userprocessor来调用远程的真实服务

### ISSUE THREAD

**Issue by wqzaxy** [sofastack/sofa-bolt#258]
### Your question
如果用sofa-bolt来做代理，是否应该在server端获取到请求后，然后通过自定义userprocessor来调用远程的真实服务

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFABolt version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by dbl-x** [comment]
这个属于你自己的业务应用，你收到请求后可以做任何操作
