### ISSUE TITLE
性能

### ISSUE THREAD

**Issue by weitingyuk** [sofastack/sofa-bolt#264]
### Your question
有没有对sofa-bolt压测数据？请问性能怎么样呢？

### Your scenes
因为netty的性能很不错，想了解一下sofa-bolt能达到什么样的吞吐

**Comment by seeflood** [comment]
我网上搜到个文档 有压测bolt+hessian
http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/assets/attach/160281/antPri58_zh/1589019232740/%E8%9A%82%E8%9A%81%E9%87%91%E8%9E%8D%E7%A7%91%E6%8A%80-%E4%B8%AD%E9%97%B4%E4%BB%B61.10.0-%E5%BE%AE%E6%9C%8D%E5%8A%A12.30.0-%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97V20200331.pdf

不过好像没有对比压测裸用netty。因为蚂蚁一直在用，性能问题倒是可以放心。不放心的话可以用自己的机器压测试试哈
