### ISSUE TITLE
Insecure Usage of JCA

### ISSUE THREAD

**Issue by akwick** [sofastack/sofa-bolt#276]
**Describe the bug**
During an empirical study to understand the nature of cryptographic misuses in enterprise-driven projects on GitHub, we randomly inspected a few of the misuses. One of the misuses for which we could confirm as a true positive of the analysis, [CogniCryptSAST](https://github.com/CROSSINGTUD/CryptoAnalysis), is in this project. 
In the class [RpcSever](https://github.com/sofastack/sofa-bolt/blob/master/src/main/java/com/alipay/remoting/rpc/RpcServer.java#L397), a key is passed as a string and that is considered insecure. In Java, strings are immutable and stay in memory until collected by Java's garbage collector. Thus, they are longer visible in memory for attackers than necessary and outside of the direct control of the developer. The suggested data types by the JCA are bytes. [JCA Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/security/crypto/CryptoSpec.html#PBEEx)

### Expected behavior
I expect a secure usage of the crypto libraries.

### Actual behavior
We observed an insecure usage of the JCA.

### Steps to reproduce

1. Apply CogniCryptSAST to the project
2. Inspect the misuses reported

### Minimal yet complete reproducer code (or GitHub URL to code)

-  In Line 397 [RpcSever](https://github.com/sofastack/sofa-bolt/blob/master/src/main/java/com/alipay/remoting/rpc/RpcServer.java#L397) the second parameter passed was previously a string (l. 390. 386)

### Environment

This API misuse still exists in the current main branch.

**Comment by chuailiwu** [comment]
welcome to submit a PR to fix it～
