### ISSUE TITLE
钉钉交流群二维码失效

### ISSUE THREAD

**Issue by jongyu** [sofastack/sofa-bolt#283]
想进入钉钉交流群,但是试了sofastack下的好几个项目的二维码扫描都提示失效

**Comment by seeflood** [comment]
二维码有一定的过期时间，群号不会过期哈
SOFAStack6群（金融级分布式架构） 钉钉群号：34197075

**Comment by jongyu** [comment]
> 有一定的过渡时间，号过渡哈 码组6（不会级导航模型组7755）

OK, 钉钉用的少, 之前有尝试用群号去搜索,也搜索不到, 后面百度搜索钉钉如何加入群聊才解决的.
感谢

**Comment by seeflood** [comment]
客气哈 我提了个pr修一下
