### ISSUE TITLE
RpcClient enableReconnectSwitch方法过时

### ISSUE THREAD

**Issue by jongyu** [sofastack/sofa-bolt#285]
### Your advice
RpcClient中的`enableReconnectSwitch()`、`enableConnectionMonitorSwitch()`方法提示已经过时，但是源码中及wiki没有提及如何使用新的方法信息

### Environment

- SOFABolt version: 
- JVM version (e.g. `java -version`): 11.0.10
- OS version (e.g. `uname -a`): macOs 12.3
- Maven version: 3.8.4
- IDE version: IntelliJ IDEA 2021.3.3

**Comment by chuailiwu** [comment]
![image](https://user-images.githubusercontent.com/2288906/160992582-36ea137e-c3d0-4d5a-b7c2-5d54cb2f95d3.png)
目前统一优化到Configuration
