### ISSUE TITLE
DefaultConnectionManager#getConnectionPoolAndCreateIfAbsent

### ISSUE THREAD

**Issue by WangShuangQuan-A** [sofastack/sofa-bolt#286]
在com.alipay.remoting.DefaultConnectionManager#getConnectionPoolAndCreateIfAbsent方法中:

RunStateRecordedFutureTask<ConnectionPool> initialTask;
initialTask是FutureTask类型，为什么直接用run方法执行？

还有 initialTask = this.connTasks.get(poolKey); 如果非空直接跳到
pool = initialTask.get();
不会一直阻塞吗？

**Comment by chuailiwu** [comment]
initialTask用FutureTask类型直接run是有点奇怪，这块我再分析看下哈
