### ISSUE TITLE
Whether to provide bolt server cluster deployment?

### ISSUE THREAD

**Issue by NobiLee** [sofastack/sofa-bolt#293]
At present, after starting the server, it is still a single machine deployment. How to solve the problem that when the server sends a message to the client, the client connects to another machine in the cluster for message forwarding

**Comment by JervyShi** [comment]
Bolt is a low-level network library and does not directly deal with service discovery scenarios. For service discovery-related capabilities, please refer to the service disovery ability in [SOFA-RPC](https://github.com/sofastack/sofa-rpc/blob/master/registry/registry-sofa/src/main/java/com/alipay/sofa/rpc/registry/sofa/SofaRegistry.java).
