### ISSUE TITLE
AbstractBatchDecoder 中的判断换种写法是不是更好理解？

### ISSUE THREAD

**Issue by MangerLe** [sofastack/sofa-bolt#318]
图中红线标注的出来的代码换成：
in.readableBytes()  >  cumulation.maxCapacity() - cumulation.writerIndex()

![image](https://user-images.githubusercontent.com/51878514/218259623-f0106f6f-90a3-47ca-9f9b-c45840506b6a.png)

**Comment by chuailiwu** [comment]
i think the concern is writeIndex

**Comment by chuailiwu** [comment]
it is good idea，hope you can create a pr for it！
