### ISSUE TITLE
Bolt can not run without hessian

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-bolt#320]
**Describe the bug**
I am going to implement a custom protocol using bolt, and I will not use hessian as a serializer. So i did not add hessian to maven. 
When bolt serializing, it will use   `com.alipay.remoting.serialization.SerializerManager#getSerializer` method to find serializer. However ,`SerializerManager` depends hessian ,so `SerializerManager` cannot initialize successfully.

If hessian is needed, change hessian's maven scope, otherwise make bolt run without hessian successfully.

- SOFABolt version: 1.6.6

**Comment by chuailiwu** [comment]
Yes, the default serialization protocol is session, so the maven scope shoud be compile.
