### ISSUE TITLE
heartbeat

### ISSUE THREAD

**Issue by Allen-Bush** [sofastack/sofa-bolt#345]
20:09:19.319 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@3fca0f6d
20:09:19.324 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded inbound message com.alipay.remoting.rpc.HeartbeatAckCommand@2b700bf5 that reached at the tail of the pipeline. Please check your pipeline configuration.
20:09:19.324 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded message pipeline : [decoder, encoder, idleStateHandler, heartbeatHandler, connectionEventHandler, handler, DefaultChannelPipeline$TailContext#0]. Channel : [id: 0x16203c22, L:/127.0.0.1:51356 - R:/127.0.0.1:1000].
20:09:19.325 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded inbound message com.alipay.remoting.rpc.HeartbeatAckCommand@5b875b3d that reached at the tail of the pipeline. Please check your pipeline configuration.
20:09:19.325 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded message pipeline : [decoder, encoder, idleStateHandler, heartbeatHandler, connectionEventHandler, handler, DefaultChannelPipeline$TailContext#0]. Channel : [id: 0x16203c22, L:/127.0.0.1:51356 - R:/127.0.0.1:1000].
20:09:34.327 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded inbound message com.alipay.remoting.rpc.HeartbeatAckCommand@e38da6f that reached at the tail of the pipeline. Please check your pipeline configuration.
20:09:34.327 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded message pipeline : [decoder, encoder, idleStateHandler, heartbeatHandler, connectionEventHandler, handler, DefaultChannelPipeline$TailContext#0]. Channel : [id: 0x16203c22, L:/127.0.0.1:51356 - R:/127.0.0.1:1000].
20:09:34.327 [bolt-netty-client-worker-1-thread-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded inbound message com.alipay.remoting.rpc.HeartbeatAckCommand@109555df that reached at the tail of the pipeline. Please check your pipeline configuration.

启动sofabolt的rpcclient与rpcserver之后一直出现这些日志

**Comment by chuailiwu** [comment]
这个DEBUG 日志可以忽略哈
